---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-netservice-bkbcs-tencent-com-v1-bcsnetpool
  failurePolicy: Fail
  name: mbcsnetpool.kb.io
  rules:
  - apiGroups:
    - netservice.bkbcs.tencent.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bcsnetpools
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-netservice-bkbcs-tencent-com-v1-bcsnetpool
  failurePolicy: Fail
  name: vbcsnetpool.kb.io
  rules:
  - apiGroups:
    - netservice.bkbcs.tencent.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - bcsnetpools
  sideEffects: None
