---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tkex.tencent.com
  resources:
  - bcsnetips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tkex.tencent.com
  resources:
  - bcsnetips/finalizers
  verbs:
  - update
- apiGroups:
  - tkex.tencent.com
  resources:
  - bcsnetips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tkex.tencent.com
  resources:
  - bcsnetpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tkex.tencent.com
  resources:
  - bcsnetpools/finalizers
  verbs:
  - update
- apiGroups:
  - tkex.tencent.com
  resources:
  - bcsnetpools/status
  verbs:
  - get
  - patch
  - update
