# permissions for end users to view bcsnetipclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bcsnetipclaim-viewer-role
rules:
- apiGroups:
  - netservice.bkbcs.tencent.com
  resources:
  - bcsnetipclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netservice.bkbcs.tencent.com
  resources:
  - bcsnetipclaims/status
  verbs:
  - get
