# permissions for end users to edit bcsnetipclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bcsnetipclaim-editor-role
rules:
- apiGroups:
  - netservice.bkbcs.tencent.com
  resources:
  - bcsnetipclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netservice.bkbcs.tencent.com
  resources:
  - bcsnetipclaims/status
  verbs:
  - get
