apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-service
  namespace: system
spec:
  type: NodePort
  ports:
  - name: https
    port: 30443
    protocol: TCP
    targetPort: 8088
  selector:
    control-plane: controller-manager
