# permissions for end users to edit bcsnetips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bcsnetip-editor-role
rules:
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - bcsnetips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - bcsnetips/status
  verbs:
  - get
