# permissions for end users to view bcsnetpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bcsnetpool-viewer-role
rules:
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - bcsnetpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - bcsnetpools/status
  verbs:
  - get
