# permissions for end users to edit bcsnetpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bcsnetpool-editor-role
rules:
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - bcsnetpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - bcsnetpools/status
  verbs:
  - get
